const { cmd } = require('../command');
const axios = require('axios'); // node-fetch වෙනුවට වඩාත් ස්ථාවර axios භාවිතය

cmd({
    pattern: "apk",
    alias: ["app", "apkdl"],
    react: "📲",
    desc: "Download APK Android Applications.",
    category: "download",
    filename: __filename
},
async (conn, mek, m, { from, quoted, q, reply, sender }) => {
    try {
        // JID එක සඳහා ආරක්ෂිතව String අගයක් ලබා ගැනීම (Crashes වැළැක්වීමට)
        const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));

        if (!q) return reply("⚠️ *Please provide the app name!*\n\n*Example:* `.apk whatsapp` or `.apk temple run`");

        // සෙවුම ආරම්භ කළ බව පෙන්වීමට පණිවිඩයක් යැවීම
        const loadingMsg = await conn.sendMessage(targetJid, { 
            text: `📲 *DENETH-MD Fetching Your APK:* \`"${q}"\`...` 
        }, { quoted: mek });

        // වඩාත් ස්ථාවර නව GiftedTech API එක මඟින් APK දත්ත ලබා ගැනීම
        const apiUrl = `https://giftedtech.my.id{encodeURIComponent(q)}`;
        const response = await axios.get(apiUrl);
        const resData = response.data;
        
        // දත්ත ලැබී ඇත්දැයි සහ සාර්ථකදැයි පරීක්ෂා කිරීම
        if (!resData || !resData.result) {
            return await conn.sendMessage(targetJid, { 
                text: "❌ *Failed to fetch APK. Application not found or server is busy!*", 
                edit: loadingMsg.key 
            });
        }

        const appData = resData.result;
        const apkName = appData.name || q;
        const downloadLink = appData.downloadUrl || appData.dllink || appData.link;
        const iconUrl = appData.icon || appData.thumbnail || "https://telegra.ph";
        const appSize = appData.size || "Unknown Size";

        let desc = `*🌤️ DENETH-MD APK DOWNLOADER 🌤️*

📦 *App Name:* ${apkName}
📊 *Size:* ${appSize}

> *Downloading application file... Please wait!* ⏳`;

        // ලෝඩින් මැසේජ් එක යාවත්කාලීන කිරීම
        await conn.sendMessage(targetJid, { text: `✅ *Application Found! Processing upload...*` }, { edit: loadingMsg.key });

        // App Icon/Thumbnail එක සමඟ විස්තර පත්‍රිකාව යැවීම
        await conn.sendMessage(
            targetJid, 
            { 
                image: { url: iconUrl }, 
                caption: desc
            }, 
            { quoted: mek }
        );
        
        // වට්සැප් එකට Document එකක් ලෙස APK ගොනුව සෘජුවම යැවීම
        await conn.sendMessage(
            targetJid, 
            { 
                document: { url: downloadLink }, 
                mimetype: "application/vnd.android.package-archive", 
                fileName: `${apkName}.apk`, 
                caption: `✅ *${apkName} Uploaded Successfully!*\n\n> *Generated by DENETH-MD* 🚀`
            }, 
            { quoted: mek }
        );

        // ක්‍රියාවලිය අවසන් වූ පසු අවසාන පණිවිඩය යාවත්කාලීන කිරීම
        return await conn.sendMessage(targetJid, { 
            text: "✅ *Application successfully delivered!*" 
        }, { edit: loadingMsg.key });
        
    } catch (e) {
        console.error(e);
        const targetJid = typeof from === 'string' ? from : (mek.key.remoteJid || String(from));
        await conn.sendMessage(targetJid, { text: "❌ *An error occurred while fetching the APK. Please try again later.*" }, { quoted: mek });
    }
});
